/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package melodia;

import dao.ManterAlbum;
import dao.ManterMusica;
import java.util.ArrayList;
import java.sql.Connection;
import static melodia.TelaAlbuns.criarConexao;
import static melodia.TelaAlbuns.encerrarConexao;

import model.Album;
import model.Musica;

/**
 *
 * @author manu
 */
public class TelaBiblioteca extends javax.swing.JFrame {
    static int codigo;
    private static Connection con = null;
    /**
     * Creates new form TelaBiblioteca
     */
    public TelaBiblioteca(int codigo) {
        this.codigo = codigo;
        initComponents();
        inicializarBiblioteca();
    }
    
    public void inicializarBiblioteca(){
        buscaAlbunsFavoritos();
        buscaMusicasFavoritas();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlbuns = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMusicas = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("Biblioteca");

        txtAlbuns.setEditable(false);
        txtAlbuns.setColumns(20);
        txtAlbuns.setRows(5);
        jScrollPane1.setViewportView(txtAlbuns);

        txtMusicas.setEditable(false);
        txtMusicas.setColumns(20);
        txtMusicas.setRows(5);
        jScrollPane2.setViewportView(txtMusicas);

        jLabel2.setText("Álbuns favoritados");

        jLabel3.setText("Músicas favoritadas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    public void buscaAlbunsFavoritos(){
        criarConexao();
        ManterAlbum listaAlbum = new ManterAlbum();
        ArrayList<String> titulos = listaAlbum.listarAlbum(con);
        for(String titulo : titulos){
            listaAlbum.listarAlbumFav(con);
        }
        encerrarConexao();
    }
    
    public void buscaMusicasFavoritas(){
        criarConexao();
        ManterMusica listMusica = new ManterMusica();
        ArrayList<String> titulos = listMusica.listarMusica(con);
        for(String titulo : titulos){
            txtMusicas.append(titulo+"\n");
            listMusica.listarMusicaFav(con);
        }
        encerrarConexao();
    }
    
     public static void encerrarConexao() {
        ConexaoBancoDados conexao = new ConexaoBancoDados();
            try {
                    con = conexao.close();
                    System.out.println("Conexão com o Banco foi encerrada.....");
            }catch (Exception e) {
                    System.out.println("Erro ao fechar a conexão: " + e.getMessage());
            }	
    }
     
     public static void criarConexao() {	
      ConexaoBancoDados conexao = new ConexaoBancoDados();
      try {
             con = conexao.getConexaoAcesso();
      }catch (Exception e) {
              System.out.println("Erro ao conectar o banco de dados: " + e.getMessage());
      }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBiblioteca(codigo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAlbuns;
    private javax.swing.JTextArea txtMusicas;
    // End of variables declaration//GEN-END:variables
}
